/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.junit.powermock;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class JupiterTest {
    @Test
    void test() {
        assertTrue(true);
    }
}
